# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_downloader_widget(object):
    def setupUi(self, custom_downloader_widget):
        custom_downloader_widget.setObjectName("custom_downloader_widget")
        custom_downloader_widget.resize(463, 162)
        self.gridLayout = QtWidgets.QGridLayout(custom_downloader_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(custom_downloader_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(self.frame)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_manipulator = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_manipulator.setObjectName("lineEdit_manipulator")
        self.gridLayout_2.addWidget(self.lineEdit_manipulator, 1, 1, 1, 1)
        self.lineEdit_download_link = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_download_link.setObjectName("lineEdit_download_link")
        self.gridLayout_2.addWidget(self.lineEdit_download_link, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_save_as = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_save_as.setObjectName("lineEdit_save_as")
        self.gridLayout_2.addWidget(self.lineEdit_save_as, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(custom_downloader_widget)
        QtCore.QMetaObject.connectSlotsByName(custom_downloader_widget)

    def retranslateUi(self, custom_downloader_widget):
        _translate = QtCore.QCoreApplication.translate
        custom_downloader_widget.setWindowTitle(_translate("custom_downloader_widget", "Form"))
        self.label_4.setText(_translate("custom_downloader_widget", "Status"))
        self.lineEdit_manipulator.setToolTip(_translate("custom_downloader_widget", "Local link manipulator has more preference over global link manipulator."))
        self.label_2.setToolTip(_translate("custom_downloader_widget", "Local link manipulator has more preference over global link manipulator."))
        self.label_2.setText(_translate("custom_downloader_widget", "Manipulator:"))
        self.label.setText(_translate("custom_downloader_widget", "Download link:"))
        self.label_3.setText(_translate("custom_downloader_widget", "Save as:"))
